### ISSUE TITLE
Please add 'xfail' status support

### ISSUE THREAD

**Issue by ysharky** [lexa/pytest-xray-server#2]
Please add 'xfail' status support or please add me access to this repo. The second way would be preferable because i have some idea for improvement.

**Comment by lexa** [comment]
Unfortunately, I've lost access to Jira Xray so even if i add `xfail` support, I can't check it.

I've added you as collaborator for the repo, feel free to submit your changes.

**Comment by ysharky** [comment]
Thank you so much. I have access to Jira Xray . I will be very careful with any changes and will check it.

Could you provide me information how to publish this module on https://pypi.org/ (https://pypi.org/project/pytest-xray-server/ )?
Ex. If I add any changes to repo who will  publish this module with a new ver 1.5? Or is it automatically?
Or should I create module with the same name by myself follows to instruction https://packaging.python.org/en/latest/tutorials/packaging-projects/?

**Comment by lexa** [comment]
>If I add any changes to repo who will publish this module with a new ver 1.5? Or is it automatically?

Unfortunately that is not automated, that is the thing I wanted to do long time ago. I'll work on automating it using Github CI.
I've created a ticket for myself to implement that: https://github.com/lexa/pytest-xray-server/issues/3. Would you prefer to update MyPy package on every commit or on every tag?

**Comment by ysharky** [comment]
I think it will be enough for each new tag with new version
