### ISSUE TITLE
Automatically deploy to PyPi on tag

### ISSUE THREAD

**Issue by lexa** [lexa/pytest-xray-server#3]
Use [Github CI/CD](https://github.com/features/actions) to automatically publish changes in the repo when it is tagged.

**Comment by ysharky** [comment]
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
could be helpful

**Comment by ysharky** [comment]
sorry for my annoyance but I would be interested to know when you plan to do this?
when we plan to get version 1.5?

**Comment by lexa** [comment]
I've merged the PR with CD to update mypy on every tag. I've created a tag 1.6 to test it; here is the github actions for it: https://github.com/lexa/pytest-xray-server/runs/6280631784?check_suite_focus=true  . On PyPi the package was also updated: https://pypi.org/project/pytest-xray-server/1.6/
